spring:
  data:
    mongodb:
      uri: mongodb+srv://chinmay####:########cluster0.t34ijqx.mongodb.net/journalDb?retryWrites=true&w=majority&appName=Cluster0
      database: journalDb
      auto-indexed-creation: true


server:
  port: 8080
  servlet:
    context-path: /journal
