spring:
  data:
    mongodb:
      uri: mongodb+srv://chinmay####:#########cluster0.t34ijqx.mongodb.net/journalDb?retryWrites=true&w=majority&appName=Cluster0
      database: journalDb
      auto-indexed-creation: true


mail:
  host: smtp.gmail.com
  port: 587
  username: chinmay8064@gmail.com
  password: lntd ptmb wvvy ahui
  properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

