spring:
  data:
    mongodb:
      uri: {mongo:uri}
      database: journalDb
      auto-indexed-creation: true


mail:
  host: smtp.gmail.com
  port: 587
  username: {mail}
  password: {mail password}
  properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

